/*
 * Product Catalog Management
 *
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 19.0 - June 2019  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 4.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The reference object to the schema and type of target service which is described by service specification
type TargetServiceSchema struct {

	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`

	// This field provides a link to the schema describing the target service
	SchemaLocation string `json:"@schemaLocation"`

	// Class type of the target service
	Type_ string `json:"@type"`
}
